### ISSUE TITLE
question in post process

### ISSUE THREAD

**Issue by JulioZhao97** [puar-playground/LACE#2]
Hi, congratulations on the excellent work!
After reading the code, I have following question:
https://github.com/puar-playground/LACE/blob/da79405c85e07fb3ef8d5577834d2191cac9714f/util/constraint.py#L273-L274
what does this operation want to achieve in post-process? 
Thanks for your patience!

**Comment by puar-playground** [comment]
This approach reverses the normalization of the height/width ratio. Since the original height/width ratio is not 1, misalignments by the same decimal value (e.g., 0.1) in the x-axis and y-axis correspond to different numbers of pixels on the original canvas. By scaling the ratio, the optimization process can penalize misalignments based on pixel distance, enhancing visual quality.
