### ISSUE TITLE
Reproducibility Issue

### ISSUE THREAD

**Issue by shunk031** [puar-playground/LACE#9]
Hi, @puar-playground

Thank you for making the source code available. I followed the instructions in the README to conduct the experiments, but I observed scores that significantly differ from the values reported in the paper. Could there be any issues that I might be missing?

As for the expected results, the FID score with post-processing should improve compared to without post-processing. However, I have observed a significant deterioration instead.

## w/o post-processing

```shell
CUDA_VISIBLE_DEVICES=0 poetry run python test.py \
    --dataset rico25 \
    --experiment all \
    --device cuda:0 \
    --dim_transformer 512 \
    --nhead 16 \
    --batch_size 2048
```

```
uncond, align: 0.11943917721509933, fid: 4.861628051666685, overlap: 81.56001281738281
cond c, align: 0.11551495641469955, fid: 3.378810726138795, maxiou: 0.337252870138345, overlap: 63.829383850097656
cond cwh, align: 0.1406959742307663, fid: 2.6824686149119543, maxiou: 0.41618777700084375, overlap: 63.829383850097656
cond complete, align: 0.12387028336524963, fid: 4.311116672084324, maxiou: 0.5355951786201641, overlap: 63.829383850097656
refine, align: 0.07545794546604156, fid: 1.9976586412695951, maxiou: 0.4811543792674452, overlap: 76.45620727539062
```

## w/ post-proccessing

```shell
CUDA_VISIBLE_DEVICES=0 poetry run python test.py \
    --dataset rico25 \
    --experiment all \
    --device cuda:0 \
    --dim_transformer 512 \
    --nhead 16 \
    --batch_size 2048 \
    --beautify
```

```
uncond, align: 0.059949640184640884, fid: 14.279923872876168, overlap: 39.159400939941406
cond c, align: 0.04224340245127678, fid: 13.644275869856301, maxiou: 0.27904064827310027, overlap: 63.829383850097656
cond cwh, align: 0.057213038206100464, fid: 12.639195848971895, maxiou: 0.35131444837828785, overlap: 63.829383850097656
cond complete, align: 0.07450857013463974, fid: 13.989529515153606, maxiou: 0.451907319782442, overlap: 63.829383850097656
refine, align: 0.02248767763376236, fid: 10.3961574566261, maxiou: 0.39940908892085836, overlap: 37.87495803833008
```

**Comment by puar-playground** [comment]
I noticed a significant change in the overlap metric in your results. It seems that the overlapping constraint may have been activated during post-processing. It should be disabled when working with the Rico dataset, and only the alignment constraint should be applied. Since overlapping is common in Rico layouts, applying the overlapping constraint can lead to a dramatic change in the FID score. 

Are you using the latest version of the source code? I remember making updates to it. As written in the lines 265-266:
https://github.com/puar-playground/LACE/blob/70d1321ed50125fb9537056506ff3930d6923514/test.py#L263C17-L266C81

**Comment by shunk031** [comment]
Thank you for your quick reply.

It seems I was using a slightly outdated code. After updating to the latest code as you pointed out, I was able to reproduce the results. Thanks!
